[package]
name = "conlang-app"
version = "0.1.0"
edition = "2021"

[dependencies]
conlang-language = { path = "../language" }
conlang-changeset = { path = "../changeset" }
conlang-persistence = { path = "../persistence" }
conlang-command = { path = "../command" }
conlang-query = { path = "../query" }
thiserror = "2"

[dev-dependencies]
conlang-generate = { path = "../generate" }
